# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/University/CPU/pipeline_CPU/pipeline_CPU.srcs/sources_1/ip/Inst_mem_0/Inst_mem_0.xci
# IP: The module: 'Inst_mem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/CPU/pipeline_CPU/pipeline_CPU.srcs/sources_1/ip/Inst_mem_0/Inst_mem_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_mem_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/University/CPU/pipeline_CPU/pipeline_CPU.srcs/sources_1/ip/Inst_mem_0/Inst_mem_0.xci
# IP: The module: 'Inst_mem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/CPU/pipeline_CPU/pipeline_CPU.srcs/sources_1/ip/Inst_mem_0/Inst_mem_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_mem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
